name: chuva_dart
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.4.3+1
  intl: ^0.19.0
  go_router: ^14.1.3
  sqflite: ^2.3.3+1
  path: ^1.9.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter
  test: any
  flutter_lints: ^2.0.0
  sqflite_common_ffi: ^2.0.0

flutter:
  uses-material-design: true
